services:
  db:
      image: postgres:latest
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: mydb
      ports:
        - "5432:5432"
  ai-service:
      build: ./ai-service
      ports:
        - "3002:3002"
      environment:
        - PYTHONUNBUFFERED=1
  backend:
      build: ./Backend
      ports:
        - "3001:3001"
      volumes:
        - ./Backend:/app
      env_file:
        - ./Backend/.env
      environment:
        - AI_SERVICE_URL=http://ai-service:3002
      depends_on:
        - db
        - ai-service
  frontend:
      build: ./road1job_next
      ports:
        - "3000:3000"
      volumes:
        - ./road1job_next:/app
      env_file:
        - ./road1job_next/.env
      depends_on:
        - backend
